"""initial migrations

Revision ID: cd07806c1dd5
Revises: 
Create Date: 2021-02-12 00:27:12.426501+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd07806c1dd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'REGULAR_USER', name='userrole'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('identity_provider', sa.Enum('GITHUB', 'ORCID', name='useridentityprovider'), nullable=True),
    sa.Column('identity_provider_user_id', sa.Integer(), nullable=True),
    sa.Column('last_identity_provider_authentication', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'identity_provider', name='identity_provider_username'),
    sa.UniqueConstraint('username', 'identity_provider_user_id', name='identity_provider_user_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.String(length=512), nullable=False),
    sa.Column('client_secret', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('NATIVE', 'SINGLE_PAGE_WEB_APP', 'REGULAR_WEB_APP', 'MACHINE_TO_MACHINE_APP', name='clienttype'), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'name', name='api_id_scope_name')
    )
    op.create_table('client_apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_api_scopes',
    sa.Column('client_api_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_api_id'], ['client_apis.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('client_api_id', 'scope_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables
    op.drop_table('client_api_scopes')
    op.drop_table('client_apis')
    op.drop_table('scopes')
    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('apis')
    # Drop enums
    user_role = sa.Enum('ADMIN', 'REGULAR_USER', name='userrole')
    user_role.drop(op.get_bind())

    client_type = sa.Enum(
        'NATIVE',
        'SINGLE_PAGE_WEB_APP',
        'REGULAR_WEB_APP',
        'MACHINE_TO_MACHINE_APP',
        name='clienttype'
    )
    client_type.drop(op.get_bind())

    user_identity_provider = sa.Enum(
        'GITHUB', 'ORCID', name='useridentityprovider'
    )
    user_identity_provider.drop(op.get_bind())
    # ### end Alembic commands ###
